apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nats
  namespace: argocd
spec:
  project: core-infrastructure
  sources:
    - repoURL: "https://nats-io.github.io/k8s/helm/charts/"
      chart: nats
      targetRevision: 1.3.14
      helm:
        valuesObject:
          tlsCA:
            enabled: false
          config:
            cluster:
              enabled: false
              tls:
                enabled: false
            jetstream:
              enabled: true
              fileStore:
                enabled: true
                dir: /data
                pvc:
                  enabled: true
                  size: 10Gi
              memoryStore:
                enabled: true
                maxSize: 1Gi
            nats:
              port: 4222
            leafnodes:
              enabled: false
            websocket:
              enabled: false
              ingress:
                enabled: false
            mqtt:
              enabled: false
            gateway:
              enabled: false
            resolver:
              enabled: false
              merge:
                type: full
                allow_delete: false
                interval: "2m"
                timeout: "1.9s"
            #   env:
            #     GOMEMLIMIT: 7GiB
            #     TOKEN:
            #       valueFrom:
            #         secretKeyRef:
            #           name: nats-auth
            #           key: token
            env: {}
          natsBox:
            enabled: false

          ################################################################################
          # Extra user-defined resources
          ################################################################################
          #
          # add arbitrary user-generated resources
          # example:
          #
          # config:
          #   websocket:
          #     enabled: true
          # extraResources:
          # - apiVersion: networking.istio.io/v1beta1
          #   kind: VirtualService
          #   metadata:
          #     name:
          #       $tplYaml: >
          #         {{ include "nats.fullname" $ | quote }}
          #     labels:
          #       $tplYaml: |
          #         {{ include "nats.labels" $ }}
          #   spec:
          #     hosts:
          #     - demo.nats.io
          #     gateways:
          #     - my-gateway
          #     http:
          #     - name: default
          #       match:
          #       - name: root
          #         uri:
          #           exact: /
          #       route:
          #       - destination:
          #           host:
          #             $tplYaml: >
          #               {{ .Values.service.name | quote }}
          #           port:
          #             number:
          #               $tplYaml: >
          #                 {{ .Values.config.websocket.port }}
          #
          extraResources: []

  destination:
    server: "https://kubernetes.default.svc"
    namespace: nats
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
