apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nats
  namespace: argocd
spec:
  project: core-infrastructure
  sources:
    - repoURL: "https://nats-io.github.io/k8s/helm/charts/"
      chart: nats
      targetRevision: 1.3.14
      helm:
        valuesObject:
          tlsCA:
            enabled: false
          config:
            cluster:
              enabled: false
              tls:
                enabled: false
            jetstream:
              enabled: true
              fileStore:
                enabled: true
                dir: /data
                pvc:
                  enabled: true
                  size: 10Gi
              memoryStore:
                enabled: true
                maxSize: 1Gi
            nats:
              port: 4222
              tls:
                enabled: true
                secretName: nats-ctrlplane-net-tls
            leafnodes:
              enabled: false
            websocket:
              enabled: false
              ingress:
                enabled: false
            mqtt:
              enabled: false
            gateway:
              enabled: false
            resolver:
              enabled: false
              merge:
                type: full
                allow_delete: false
                interval: "2m"
                timeout: "1.9s"
            #   env:
            #     GOMEMLIMIT: 7GiB
            #     TOKEN:
            #       valueFrom:
            #         secretKeyRef:
            #           name: nats-auth
            #           key: token
            env: {}
          natsBox:
            enabled: false
          extraResources:
            - apiVersion: cert-manager.io/v1
              kind: Certificate
              metadata:
                name: nats-ctrlplane-net-tls
                namespace: nats
              spec:
                secretName: nats-ctrlplane-net-tls
                duration: 2160h0m0s # 90d
                renewBefore: 360h0m0s # 15d
                subject:
                  organizations:
                    - ctrlplane
                commonName: nats.ctrlplane.net
                privateKey:
                  algorithm: ECDSA
                usages:
                  - server auth
                  - client auth
                dnsNames:
                  - nats.ctrlplane.net
                issuerRef:
                  name: letsencrypt
                  kind: ClusterIssuer
            - apiVersion: v1
              kind: Service
              metadata:
                name: nats-public
              spec:
                type: LoadBalancer
                selector:
                  app.kubernetes.io/component: nats
                  app.kubernetes.io/instance: nats
                  app.kubernetes.io/name: nats
                ports:
                  - port: 4222
                    targetPort: 4222
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nats
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
