---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
spec:
  project: core-infrastructure
  sources:
    - repoURL: "https://kyverno.github.io/kyverno"
      targetRevision: 3.5.1
      chart: kyverno
      helm:
        values: |
          crds:
            migration:
              enabled: false
    - repoURL: "https://github.com/ekwisnek/argocd.git"
      targetRevision: HEAD
      path: extra-manifests/kyverno-policies
      directory:
        recurse: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
