apiVersion: cluster.redpanda.com/v1alpha2
kind: Redpanda
metadata:
  name: redpanda
spec:
  clusterSpec:
    storage:
      persistentVolume:
        size: 5Gi
    external:
      domain: customredpandadomain.local
    statefulset:
      podAntiAffinity:
        type: soft
        topologyKey: kubernetes.io/hostname
    #   initContainers:
    #     setDataDirOwnership:
    #       enabled: true
