apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitwarden-cli
  namespace: argocd
spec:
  project: core-infrastructure
  source:
    repoURL: "https://github.com/ekwisnek/argocd.git"
    directory:
      recurse: true
      exclude: credential-secret.yaml
    path: /extra-manifests/bitwarden
  destination:
    server: "https://kubernetes.default.svc"
    namespace: bitwarden
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true