---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coroot-operator
  namespace: argocd
spec:
  project: core-infrastructure
  sources:
    - repoURL: "https://coroot.github.io/helm-charts"
      targetRevision: 0.4.2
      chart: coroot-operator
  destination:
    server: "https://kubernetes.default.svc"
    namespace: coroot
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
