apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tracee
  namespace: argocd
spec:
  destination:
    namespace: tracee
    server: https://kubernetes.default.svc
  project: core-infrastructure
  sources:
    - repoURL: https://aquasecurity.github.io/helm-charts/
      targetRevision: 0.24.1
      chart: tracee
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
