apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy-operator
  namespace: argocd
spec:
  destination:
    namespace: trivy-operator
    server: https://kubernetes.default.svc
  project: core-infrastructure
  sources:
    - repoURL: https://aquasecurity.github.io/helm-charts/
      targetRevision: 0.29.3
      chart: trivy-operator
      helm:
        values: |
          trivy:
            storageClassEnabled: true
            storageClassName: "local-path"
            storageSize: "5Gi"
            severity: HIGH,CRITICAL,MEDIUM,LOW,UNKNOWN
            slow: false
            ignoreUnfixed: true
            mode: ClientServer
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
          operator:
            builtInTrivyServer: true
            replicas: 1
            configAuditScannerEnabled: true
            rbacAssessmentScannerEnabled: true
            infraAssessmentScannerEnabled: true
            clusterComplianceEnabled: true
            exposedSecretScannerEnabled: true
            metricsFindingsEnabled: true
            metricsVulnIdEnabled: true
            metricsExposedSecretInfo: true
            metricsConfigAuditInfo: true
            metricsRbacAssessmentInfo: true
            metricsInfraAssessmentInfo: true
            metricsImageInfo: true
            metricsClusterComplianceInfo: true
          securityContext:
            runAsNonRoot: true
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
