apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy-operator
  namespace: argocd
spec:
  destination:
    namespace: trivy-operator
    server: https://kubernetes.default.svc
  project: core-infrastructure
  sources:
    - repoURL: https://aquasecurity.github.io/helm-charts/
      targetRevision: 0.31.0
      chart: trivy-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
