---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: core-infrastructure
  sources:
    - repoURL: "https://charts.jetstack.io"
      targetRevision: v1.18.2
      chart: cert-manager
      helm:
        valuesObject:
          featureGates: "AdditionalCertificateOutputFormats=true"
          disableAutoApproval: false
          webhook:
            featureGates: "AdditionalCertificateOutputFormats=true"
          crds:
            enable: true
          extraObjects:
            - apiVersion: cert-manager.io/v1
              kind: ClusterIssuer
              metadata:
                name: letsencrypt
                annotations:
                  argocd.argoproj.io/hook: PostSync
              spec:
                acme:
                  email: evankwisnek@gmail.com
                  server: https://acme-v02.api.letsencrypt.org/directory
                  privateKeySecretRef:
                    name: letsencrypt-issuer-key
                  solvers:
                    - dns01:
                        cloudflare:
                          email: evankwisnek@gmail.com
                          apiKeySecretRef:
                            name: cloudflare-api-token-secret
                            key: api-token
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true