---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: core-infrastructure
  sources:
    - repoURL: "https://charts.jetstack.io"
      targetRevision: v1.18.2
      chart: cert-manager
      helm:
        valuesObject:
          config:
            enableGatewayAPI: true
          featureGates: "AdditionalCertificateOutputFormats=true"
          disableAutoApproval: false
          webhook:
            featureGates: "AdditionalCertificateOutputFormats=true"
          crds:
            enabled: true
    - repoURL: "https://github.com/ekwisnek/argocd.git"
      targetRevision: HEAD
      path: extra-manifests/cert-manager
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
