apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: core-infrastructure
  namespace: argocd
spec:
  description: Core Infrastructure Project
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'