apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd
spec:
  project: core-infrastructure
  sources:
    - repoURL: "https://charts.external-secrets.io"
      chart: external-secrets
      targetRevision: 0.9.19
    - repoURL: "https://github.com/ekwisnek/argocd.git"
      targetRevision: HEAD
      path: extra-manifests/external-secrets-operator
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
