apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: contour
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: core-infrastructure
  sources:
    - helm:
        valuesObject:
          envoy:
            service:
              type: NodePort
            nodePorts:
              http: 30080
              https: 30443
              metrics: 8002
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 21.0.10 
      chart: contour
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
