apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: contour
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: core-infrastructure
  sources:
    - helm:
        valuesObject:
          contour:
            extraArgs:
              - --use-proxy-protocol
          envoy:
            service:
              type: NodePort
              nodePorts:
                http: 30080
                https: 30443
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 21.0.10 
      chart: contour
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
