apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
spec:
  destination:
    namespace: argo-workflows
    server: https://kubernetes.default.svc
  project: core-infrastructure
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 0.45.10
      chart: argo-workflows
      helm:
        valuesObject:
          server:
            authModes:
              - sso
            sso:
              enabled: true
              issuer: https://argocd.ctrlplane.net/api/dex
              clientId:
                name: argo-workflows-sso
                key: client-id
              clientSecret:
                name: argo-workflows-sso
                key: client-secret
              redirectUrl: https://workflows.ctrlplane.net/oauth2/callback
            ingress:
              enabled: false
              annotations:
                cert-manager.io/cluster-issuer: letsencrypt
                kubernetes.io/tls-acme: "true"
                nginx.ingress.kubernetes.io/ssl-passthrough: "true"
                nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
              ingressClassName: "nginx"
              hosts:
                - workflows.ctrlplane.net
              paths:
                - /
              tls:
                - secretName: argoworkflows-ui-tls
                  hosts:
                    - workflows.ctrlplane.net
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
