apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-kafka-operator
  namespace: argocd
spec:
  project: core-infrastructure
  destination:
    namespace: strimzi-kafka-operator
    server: https://kubernetes.default.svc
  sources:
    - repoURL: oci://quay.io/strimzi-helm
      chart: strimzi-kafka-operator
      targetRevision: 0.49.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
