apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
  namespace: argocd
spec:
  destination:
    namespace: argo-events
    server: https://kubernetes.default.svc
  project: argocd
  sources:
    - helm:
        valuesObject:
          extraObjects:
            - |
              apiVersion: argoproj.io/v1alpha1
              kind: EventBus
              metadata:
                name: nats-js-eventbus
                namespace: argo-events
              spec:
                jetstream:
                  version: latest
                  persistence:
                    volumeSize: 2Gi
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: v1.9.7
      chart: argo-events
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
