apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
  namespace: argocd
spec:
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  project: core-infrastructure
  sources:
    - helm:
        valuesObject:
          configs:
            jetstream:
              streamConfig:
                maxBytes: 1GB
          extraObjects:
            - |
              apiVersion: argoproj.io/v1alpha1
              kind: EventBus
              metadata:
                argocd.argoproj.io/sync-wave: "5"
                name: nats-js-eventbus
                namespace: argo
              spec:
                jetstream:
                  version: latest
                  persistence:
                    volumeSize: 2Gi
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 2.4.16
      chart: argo-events
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
