apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: externalsecrets.external-secrets.io
spec:
  versions:
    - name: v1beta1
      served: true
      deprecated: true
      deprecationWarning: "external-secrets.io/v1beta1 is deprecated; use external-secrets.io/v1"
